services:
  make-it-real:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - localai
      - mcp-github
  localai:
    image: localai/localai:v3.1.1-vulkan
    privileged: true
    ports:
    - "8080:8080"
    volumes:
      - "localai-models:/models"
      - "localai-backends:/backends"

  mcp-github:
    image: ghcr.io/github/github-mcp-server
    stdin_open: true
    env_file: .mcp.env
volumes:
  localai-models:
  localai-backends: